// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members

// 📦 Package imports:
// ignore: depend_on_referenced_packages

// 📦 Package imports:
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;

import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC17pF2ulwqaUIk6P0Om_DR6fPQvaCwK4Q',
    appId: '1:684367942296:web:df9b3c99896396269c76ed',
    messagingSenderId: '684367942296',
    projectId: 'ananas-59161',
    authDomain: 'ananas-59161.firebaseapp.com',
    storageBucket: 'ananas-59161.appspot.com',
    measurementId: 'G-C0M7SW6LL6',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA4Qkw6yA045mtevTJ35ojYZa_K3D8KIJ4',
    appId: '1:684367942296:android:25ea39400ed2afb99c76ed',
    messagingSenderId: '684367942296',
    projectId: 'ananas-59161',
    storageBucket: 'ananas-59161.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDxT5wtYmhGUWnIIjzjrPOlgVoTgiJ28EE',
    appId: '1:684367942296:ios:de49251c7c38edb79c76ed',
    messagingSenderId: '684367942296',
    projectId: 'ananas-59161',
    storageBucket: 'ananas-59161.appspot.com',
    iosBundleId: 'com.example.ananas',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDxT5wtYmhGUWnIIjzjrPOlgVoTgiJ28EE',
    appId: '1:684367942296:ios:2e797c0f1e3764559c76ed',
    messagingSenderId: '684367942296',
    projectId: 'ananas-59161',
    storageBucket: 'ananas-59161.appspot.com',
    iosBundleId: 'com.example.ananas.RunnerTests',
  );
}
